version: '3.8'

services:
  # FastAPI Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-groq-backend
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - APP_NAME=Simple Groq App
      - APP_VERSION=1.0.0
      - DEBUG=True
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8000
      - ALLOWED_ORIGINS=http://localhost:8501,http://frontend:8501
    volumes:
      - .:/app
    command: uv run python -m uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  # Streamlit Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-groq-frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    volumes:
      - .:/app
    command: uv run python -m streamlit run frontend/app.py --server.address 0.0.0.0 --server.port 8501 --server.headless true
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app-data:
